config/routes.rb
QualityCloud::Application.routes.draw do

  get 'calls/:call_id/notes' => "call_notes#call_notes"
  resources :call_notes

  get '/users/:user_id/saved_search_tabs' => "saved_search_tabs#user_saved_tabs"
  get '/users/current_user_saved_search_tabs' => "saved_search_tabs#current_user_saved_tabs"
  resources :saved_search_tabs

  match '/organization' => "home#personal", as: :personal_tab
  match '/search' => "home#search", as: :search_tab
  get '/settings' => "home#settings", as: :settings_tab
  
  resources :roles do
    member do
      put :set_permissions
    end
  end
  
  match "/permissions" => "roles#permissions"

  resources :groups do
    resources :users, only: [] do
      collection do
        get "/", action: :group_members
      end
    end
  end

  get 'calls/download_calls' => "calls#download_calls"
  get 'calls/:id/stream_video' => "calls#stream_video"
  get 'calls/:id/stream_audio' => "calls#stream_audio"
  match '/calls/search' => "calls#search"
  match '/calls/load_calls' => "calls#load_calls"
  resources :calls do 
    member do
      get :status
    end
  end

  resources :dashboard, only: [ :index ]
  resources :searches, only: [ :index, :create ], controller: :search, path: '/search'

  get '/admin/users/:id/user_avatar/:type' => "users#user_avatar"
  get '/admin/users/user_names' => "users#user_names"
  scope :admin, path: '/admin' do
    resources :users do
      collection { post :import }
    end
  end
  
  devise_for :users, :controllers => { :passwords => "passwords" }
  authenticated :user do
    root :to => 'home#search'
  end
  get "home/email_confirmation" => "home#email_confirmation"

  unauthenticated :user do
    devise_scope :user do 
      get "/" => "devise/sessions#new"
    end
  end

  resources :assigned_roles
  resources :role_accesses

end

app/models/saved_search_tab.rb
class SavedSearchTab < ActiveRecord::Base
  attr_accessible :name, :search_params, :user_id

  belongs_to :user

  validates :name, :uniqueness => {:scope => :user_id}
end

# == Schema Information
#
# Table name: saved_search_tabs
#
#  id            :integer          not null, primary key
#  user_id       :integer
#  search_params :string(255)
#  name          :string(255)
#  created_at    :datetime         not null
#  updated_at    :datetime         not null
#

app/controllers/saved_search_tabs_controller.rb
class SavedSearchTabsController < ApplicationController
  
  load_and_authorize_resource
  # GET /users/:user_id/saved_search_tabs
  def user_saved_tabs
    @saved_search_tabs = User.find(params[:user_id]).saved_search_tabs

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @saved_search_tabs }
    end
  end

  # GET /users/current_user_saved_search_tabs
  def current_user_saved_tabs
    @saved_search_tabs = current_user.saved_search_tabs

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @saved_search_tabs }
    end
  end

  # GET /saved_search_tabs
  # GET /saved_search_tabs.json
  def index
    @saved_search_tabs = SavedSearchTab.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @saved_search_tabs }
    end
  end

  # GET /saved_search_tabs/1
  # GET /saved_search_tabs/1.json
  def show
    @saved_search_tab = SavedSearchTab.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @saved_search_tab }
    end
  end

  # GET /saved_search_tabs/new
  # GET /saved_search_tabs/new.json
  def new
    @saved_search_tab = SavedSearchTab.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @saved_search_tab }
    end
  end

  # GET /saved_search_tabs/1/edit
  def edit
    @saved_search_tab = SavedSearchTab.find(params[:id])
  end

  # POST /saved_search_tabs
  # POST /saved_search_tabs.json
  def create
    @saved_search_tab = SavedSearchTab.new(params[:saved_search_tab])

    respond_to do |format|
      if @saved_search_tab.save
        format.html { redirect_to @saved_search_tab, notice: 'Saved search tab was successfully created.' }
        format.json { render json: @saved_search_tab, status: :created, location: @saved_search_tab }
      else
        format.html { render action: "new" }
        format.json { render json: @saved_search_tab.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /saved_search_tabs/1
  # PUT /saved_search_tabs/1.json
  def update
    @saved_search_tab = SavedSearchTab.find(params[:id])

    respond_to do |format|
      if @saved_search_tab.update_attributes(params[:saved_search_tab])
        format.html { redirect_to @saved_search_tab, notice: 'Saved search tab was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @saved_search_tab.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /saved_search_tabs/1
  # DELETE /saved_search_tabs/1.json
  def destroy
    @saved_search_tab = SavedSearchTab.find(params[:id])
    @saved_search_tab.destroy

    respond_to do |format|
      format.html { redirect_to saved_search_tabs_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/saved_search_tabs_helper.rb
module SavedSearchTabsHelper
end

app/views/saved_search_tabs/_form.html.haml
= form_for @saved_search_tab do |f|
  - if @saved_search_tab.errors.any?
    #error_explanation
      %h2= "#{pluralize(@saved_search_tab.errors.count, "error")} prohibited this saved_search_tab from being saved:"
      %ul
        - @saved_search_tab.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :user_id
    = f.number_field :user_id
  .field
    = f.label :search_params
    = f.text_field :search_params
  .field
    = f.label :name
    = f.text_field :name
  .actions
    = f.submit 'Save'

app/views/saved_search_tabs/edit.html.haml
%h1 Editing saved_search_tab

= render 'form'

= link_to 'Show', @saved_search_tab
\|
= link_to 'Back', saved_search_tabs_path

app/views/saved_search_tabs/index.html.haml
%h1 Listing saved_search_tabs

%table
  %tr
    %th User
    %th Search params
    %th Name
    %th
    %th
    %th

  - @saved_search_tabs.each do |saved_search_tab|
    %tr
      %td= saved_search_tab.user_id
      %td= saved_search_tab.search_params
      %td= saved_search_tab.name
      %td= link_to 'Show', saved_search_tab
      %td= link_to 'Edit', edit_saved_search_tab_path(saved_search_tab)
      %td= link_to 'Destroy', saved_search_tab, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Saved search tab', new_saved_search_tab_path

app/views/saved_search_tabs/new.html.haml
%h1 New saved_search_tab

= render 'form'

= link_to 'Back', saved_search_tabs_path

app/views/saved_search_tabs/show.html.haml
%p#notice= notice

%p
  %b User:
  = @saved_search_tab.user_id
%p
  %b Search params:
  = @saved_search_tab.search_params
%p
  %b Name:
  = @saved_search_tab.name

= link_to 'Edit', edit_saved_search_tab_path(@saved_search_tab)
\|
= link_to 'Back', saved_search_tabs_path