config/routes.rb
QualityCloud::Application.routes.draw do

  get 'calls/:call_id/notes' => "call_notes#call_notes"
  resources :call_notes

  get '/users/:user_id/saved_search_tabs' => "saved_search_tabs#user_saved_tabs"
  get '/users/current_user_saved_search_tabs' => "saved_search_tabs#current_user_saved_tabs"
  resources :saved_search_tabs

  match '/organization' => "home#personal", as: :personal_tab
  match '/search' => "home#search", as: :search_tab
  get '/settings' => "home#settings", as: :settings_tab
  
  resources :roles do
    member do
      put :set_permissions
    end
  end
  
  match "/permissions" => "roles#permissions"

  resources :groups do
    resources :users, only: [] do
      collection do
        get "/", action: :group_members
      end
    end
  end

  get 'calls/download_calls' => "calls#download_calls"
  get 'calls/:id/stream_video' => "calls#stream_video"
  get 'calls/:id/stream_audio' => "calls#stream_audio"
  match '/calls/search' => "calls#search"
  match '/calls/load_calls' => "calls#load_calls"
  resources :calls do 
    member do
      get :status
    end
  end

  resources :dashboard, only: [ :index ]
  resources :searches, only: [ :index, :create ], controller: :search, path: '/search'

  get '/admin/users/:id/user_avatar/:type' => "users#user_avatar"
  get '/admin/users/user_names' => "users#user_names"
  scope :admin, path: '/admin' do
    resources :users do
      collection { post :import }
    end
  end
  
  devise_for :users, :controllers => { :passwords => "passwords" }
  authenticated :user do
    root :to => 'home#search'
  end
  get "home/email_confirmation" => "home#email_confirmation"

  unauthenticated :user do
    devise_scope :user do 
      get "/" => "devise/sessions#new"
    end
  end

  resources :assigned_roles
  resources :role_accesses

end

app/models/group.rb
class Group < ActiveRecord::Base
  attr_accessible :name, :role_ids, :creator
  attr_accessor :creator, :new_group_id

  has_many :assigned_roles, dependent: :destroy, as: :roleable
  has_many :roles, through: :assigned_roles, source: :role
  has_many :users

  validates :name, :presence => true
  validates :name, :uniqueness => {:case_sensitive => false}
  validate :must_have_role

  default_scope order('groups.name ASC')

  after_commit :give_user_access_to_group
  before_destroy :check_preset_groups
  after_destroy :assign_users_to_new_group
  before_save :check_preset_groups_attributes

  def assign_users_to_new_group
    self.users.update_all :group_id => self.new_group_id
  end

  def must_have_role
    if roles.empty? or roles.all? {|role| role.marked_for_destruction? }
      errors.add(:groups, 'must have at least one role')
    end
  end

  def has_role?
    ! (roles.empty? or roles.all? {|role| role.marked_for_destruction? })
  end

  def has_other_role? deleted_role
    ! (roles.empty? or roles.all? {|role| role.id == deleted_role.id })
  end

  def give_user_access_to_group
    role = creator.try(:roles).try(:first)
    if role
      role.role_accesses.create(:accessable_id => self.id, :accessable_type => "Group")
    end
  end

  def check_preset_groups
    if name == configatron.default_group_name
      self.errors[:base] << "Cannot delete '#{configatron.default_group_name}' group."
      return false  
    # Alert: SUPER_USER
    elsif name == configatron.super_group_name  
      self.errors[:base] << "Cannot delete '#{configatron.super_group_name}' group."
      return false  
    end 
  end

  # make sure that the preset groups aren't changed
  def check_preset_groups_attributes
    # Alert: SUPER_USER
    if self.name_was == configatron.super_group_name
      self.name = configatron.super_group_name
    elsif self.name_was == configatron.default_group_name
      self.name = configatron.default_group_name
    end
  end

  #---------Super User---------#
  # Alert: SUPER_USER
  def is_super?
    name == configatron.super_group_name
  end

  def as_json(*args)
    #TODO: refactor convert to jbuilder
    hash = super(*args)
    hash.merge!({:roles=> self.roles})
    hash
  end
end

# == Schema Information
#
# Table name: groups
#
#  id         :integer          not null, primary key
#  name       :string(255)      default(""), not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_filter :selected_item
  load_and_authorize_resource
  # GET /groups
  # GET /groups.json
  def index
    @groups = current_user.accessed_groups

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @groups }
    end
  end

  # GET /groups/1
  # GET /groups/1.json
  def show
    @group = Group.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @group }
    end
  end

  # GET /groups/new
  # GET /groups/new.json
  def new
    @group = Group.new
    @roles = Role.all()

    respond_to do |format|
      format.html { render partial: 'form', layout: false }
      format.json { render json: @group }
    end
  end

  # GET /groups/1/edit
  def edit
    @group = Group.find(params[:id])
    @roles = Role.all()
    if @group.blank?
      "Group doesn't exist"
    else
      respond_to do |format|
        format.html { render partial: 'form', layout: false }
        format.json { render json: @group }
      end
    end
  end

  # POST /groups
  # POST /groups.json
  def create
    @group = Group.new(params[:group].merge(:creator => current_user))
    unless current_user.has_permissions? [:assign_roles_group_tab]
      @group.role_ids = current_user.roles.map(&:id)
    end
    respond_to do |format|
      if @group.save
        format.html { redirect_to @group, notice: 'Group was successfully created.' }
        format.json { render json: @group, status: :created }
      else
        format.html { render action: "new" }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /groups/1
  # PUT /groups/1.json
  def update
    @group = Group.find(params[:id])
    unless current_user.has_permissions? [:assign_roles_group_tab]
      params[:group].delete :role_ids
    end
    unless current_user.has_permissions? [:modify_groups]
      params[:group].slice! :role_ids
    end


    respond_to do |format|
      if @group.update_attributes(params[:group])
        format.html { redirect_to @group, notice: 'Group was successfully updated.' }
        format.json { render json: @group.to_json , status: :created }
      else
        format.html { render action: "edit" }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /groups/1
  # DELETE /groups/1.json
  def destroy
    new_group_id = params[:new_group_id]
    @group = Group.find(params[:id])
    @group.new_group_id = new_group_id
    @group.destroy

    respond_to do |format|
      format.html { redirect_to groups_url }
      format.json { head :no_content }
    end
  end

  private
  def selected_item
    @selected = :personal
    @sub_menue = :groups
  end
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/groups/_form.html.haml
#errors_container.ui-tooltip.alert.alert-error.js-alert-errors.hide-it{style:"max-width: 300px;margin: 10px;"}
  %h4 Errors!
  %p.errors.ui-tooltip{style: 'margin-top:0px;margin-bottom:0px;'}
= form_for @group do |f|
  .control-group.nw-gurp-role-top
    = f.label "Goup Name", class: 'control-label'
    .nw-gurp-role-inpt
      = f.text_field :name, class: 'text_field'
  #js_role_btns.new-role-option-wrapper
    .available-users-group.boxLayout
      .available-users.fl Roles

      #checkboxes.w-100.fl.scroll-list 
        - @roles.each do |role|
          .list-white.fl
            = hidden_field_tag "group_role_ids_none", nil, {:name => "group[role_ids][]"}
            = check_box_tag "group_role_ids_#{role.id}", role.id, (f.object.roles.present? && f.object.roles.include?(role)), {:name => "group[role_ids][]"}
            = label_tag "group_role_ids_#{role.id}", role.name
  / Hidden submit button, to allow submit form on enter key
  .hidden-submit
    %input{:type => "submit", :tabindex => -1}

app/views/groups/edit.html.haml
- model_class = Group
.page-header
  %h1=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

app/views/groups/index.html.haml
- model_class = Group

%table.table.table-striped
  %thead
    %tr
      %th= model_class.human_attribute_name(:name)
      %th= model_class.human_attribute_name(:role)
      %th=t '.actions', :default => t("helpers.actions")
  %tbody
    - @groups.each do |group|
      %tr
        %td= link_to group.name, group_path(group)
        %td= group.role.name
        %td
          = link_to t('.edit', :default => t("helpers.links.edit")), edit_group_path(group), :class => 'btn btn-mini'
          = link_to t('.destroy', :default => t("helpers.links.destroy")), group_path(group), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-mini btn-danger'
%br

= link_to 'New Group', new_group_path, :class => 'btn'

app/views/groups/new.html.haml
%h1 New group

= render 'form'

= link_to 'Back', groups_path

app/views/groups/show.html.haml
- model_class = Group
.page-header
  %h1=t '.title', :default => model_class.model_name.human.titleize

%p
  %strong= model_class.human_attribute_name(:name) + ':'
  %br
  = @group.name
%p
  %strong= model_class.human_attribute_name(:role) + ':'
  %br
  = @group.role.name

.form-actions
  = link_to t('.back', :default => t("helpers.links.back")), groups_path, :class => 'btn'
  = link_to t('.edit', :default => t("helpers.links.edit")), edit_group_path(@group), :class => 'btn'
  = link_to t('.destroy', :default => t("helpers.links.destroy")), group_path(@group), :method => "delete", :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-danger'