config/routes.rb
QualityCloud::Application.routes.draw do

  get 'calls/:call_id/notes' => "call_notes#call_notes"
  resources :call_notes

  get '/users/:user_id/saved_search_tabs' => "saved_search_tabs#user_saved_tabs"
  get '/users/current_user_saved_search_tabs' => "saved_search_tabs#current_user_saved_tabs"
  resources :saved_search_tabs

  match '/organization' => "home#personal", as: :personal_tab
  match '/search' => "home#search", as: :search_tab
  get '/settings' => "home#settings", as: :settings_tab
  
  resources :roles do
    member do
      put :set_permissions
    end
  end
  
  match "/permissions" => "roles#permissions"

  resources :groups do
    resources :users, only: [] do
      collection do
        get "/", action: :group_members
      end
    end
  end

  get 'calls/download_calls' => "calls#download_calls"
  get 'calls/:id/stream_video' => "calls#stream_video"
  get 'calls/:id/stream_audio' => "calls#stream_audio"
  match '/calls/search' => "calls#search"
  match '/calls/load_calls' => "calls#load_calls"
  resources :calls do 
    member do
      get :status
    end
  end

  resources :dashboard, only: [ :index ]
  resources :searches, only: [ :index, :create ], controller: :search, path: '/search'

  get '/admin/users/:id/user_avatar/:type' => "users#user_avatar"
  get '/admin/users/user_names' => "users#user_names"
  scope :admin, path: '/admin' do
    resources :users do
      collection { post :import }
    end
  end
  
  devise_for :users, :controllers => { :passwords => "passwords" }
  authenticated :user do
    root :to => 'home#search'
  end
  get "home/email_confirmation" => "home#email_confirmation"

  unauthenticated :user do
    devise_scope :user do 
      get "/" => "devise/sessions#new"
    end
  end

  resources :assigned_roles
  resources :role_accesses

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :selected_item
  before_filter :process_create_params, only: [:create, :update]
  after_filter :set_pagination_headers, only: :index
  # Authorization
  load_and_authorize_resource

  # GET /users
  # GET /users.json
  def index
    @users = current_user.accessed_users
    @users = @users.filter_users_and_users_group(params[:filter_users]) unless params[:filter_users].blank?
    @users = @users.order_joins(params[:order_by]) unless params[:order_by].blank?
    @users = @users.where("group_id = ?", params[:group_id]) if params[:group_id]
    if params[:search_params]
      @users = @users.uninheriters if params[:search_params][:uninherited]
    end
    @users = @users.paginate pagination_options
    respond_to do |format|
      format.html # index.html.erb
      # format.json {render "index"}
      format.json { render json: @users.to_json(:include =>  
            {:supervisor => {:only => [:first_name, :last_name]},
            :group => {:only => [:name]}})  }
            # :role => {:only => [:name]}})  }
    end
  end

  def new
    @user = User.new
    @roles = Role.all
    @groups = current_user.accessed_groups

    respond_to do |format|
      format.html { render partial: 'form', layout: false }
      format.json { render json: @user }
    end
  end

  def create
    params[:user].delete(:avatar) if params[:user][:avatar].blank?
    @user = User.new(params[:user].merge(:creator => current_user))

    respond_to do |format|
      if @user.save
        # format.html { redirect_to users_url, notice: 'User was successfully created.' }
        format.json { render json: @user.to_json(:include =>  
            {:supervisor => {:only => [:first_name, :last_name]},
            :group => {:only => [:name]},
            :role => {:only => [:name]}})  }
      else
        # format.html { render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user.to_json(:include =>  
            {:supervisor => {:only => [:first_name, :last_name]},
            :group => {:only => [:name]},
            :role => {:only => [:name]}})  }
    end
  end

  def user_names
    @users = current_user.accessed_users #TODO till we fix the jBuilders .select("id, first_name, last_name")
    respond_to do |format|
      format.json { render json: @users }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
    if @user.blank?
      "User doesn't exist"
    else
      @roles = Role.all
      @groups = current_user.accessed_groups
      
      respond_to do |format|
        format.html { render partial: 'form', layout: false }
        format.json { render json: @user }
      end
    end
  end

  
  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find params[:id]
    error = false
    password_changed = false
    if params[:user][:password].blank?
      params[:user].delete("password")
      params[:user].delete("password_confirmation")
    # if current user has no permission to change password
    elsif !@user.change_password && current_user == @user && !@user.has_permissions?([:change_user_password])
      error = true # raise error and don't continue with update
    # if successfully changed password of current user
    elsif @user.change_password && (current_user == @user)
      password_changed = true # bypass the user and sign him in with the new password
    end

    unless @user.has_permissions? [:assign_roles_user_tab]
      params[:user].delete :roles
    end
    
    respond_to do |format|
      if !error && @user.update_attributes(params[:user].merge(:creator => current_user))
        if password_changed
          # refresh credentials in the session
          sign_out(current_user)
          sign_in(@user, :bypass => true)
        end
        format.html { redirect_to settings_tab_url }
        format.json { render json: @user.to_json(:include =>  
          {:supervisor => {:only => [:first_name, :last_name]},
          :group => {:only => [:name]},
          :role => {:only => [:name]}}) , status: :ok }
      else
        if params[:settings] && current_user
          if current_user.update_attribute('settings',params[:settings])
            format.json { render json: current_user}
          end
        else
          @user.errors.add(:password, "You don't have permission to change it") if error
          flash[:errors] = @user.errors.full_messages
          format.html { redirect_to settings_tab_url}
          format.json { render json: @user.errors, status: :unprocessable_entity }
        end

      end
    end
  end

  def import
    # counter = User.import(params[:file])
    # redirect_to personal_tab_url, notice: "#{counter} Users imported successfully."
    users = User.import(params[:file], current_user)
    respond_to do |format|
      format.html { redirect_to personal_tab_url, notice: "#{users[:valid_users].count} Users imported successfully out of #{users[:invalid_users].count} records."}
      format.json { 
        json_valid_users = users[:valid_users].to_json(:include =>  
            {:supervisor => {:only => [:first_name, :last_name]},
            :group => {:only => [:name]}})  
        json_invalid_users = users[:invalid_users].to_json(:include =>  
            {:supervisor => {:only => [:first_name, :last_name]},
            :group => {:only => [:name]}},
            :methods => [:errors] )  
        render json: {:valid_users => json_valid_users, :invalid_users => json_invalid_users}.to_json
      }
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json

  def destroy
    unless @user == current_user
      @user.creator = current_user
      @user.destroy
    end

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end

  # GET /groups/:group_id/non_users
  def group_members
    @users = if params[:members].blank? or params[:members] == "true"
      current_user.accessed_users.where("group_id = ?", params[:group_id])
    else
      current_user.accessed_users.where("group_id != ? or group_id IS NULL", params[:group_id])
    end
    respond_to do |format|
      format.json { render json: @users }
    end
  end

  def user_avatar
    avatar_path = User.find(params[:id]).avatar.path(params[:type])
    avatar_path ||= "#{Rails.root}/public/system/avatars/#{params[:type]}/missing.png"
    
    respond_to do |format|
      format.html { send_data open(avatar_path) {|f| f.read }, :filename => "user_#{params[:id]}", :type => 'image' }
    end
  end

  private
  def set_pagination_headers
    headers["X-Pagination"] = {      
        total_pages: @users.total_pages,
        total_entries: @users.total_entries,
        start_entry: @users.offset,
        end_entry: @users.offset+@users.length
      }.to_json
  end
  def selected_item
    @selected = :personal
    @sub_menue = :users
  end

  def init_user
    @user = User.new(params[:user], as: :admin)
  end

  def process_create_params
    params[:user].delete(:avatar) if params[:user][:avatar].blank?
  end

end

app/helpers/users_helper.rb
module UsersHelper
	def user_types_options
		User::TYPES.map{ |type| [type, type.titleize.gsub(/\s+/, '').constantize] }
	end

  def supervisors_list
    current_user.accessed_users.supervisables.map{ |user| [user.name, user.id] }
  end

  def groups_list
    current_user.accessed_groups.map{ |group| [group.name, group.id] }
  end
end

app/views/users/_form.html.haml
#errors_container.ui-tooltip.alert.alert-error.js-alert-errors.hide-it
  %h4 Errors!
  %p.errors.ui-tooltip{style: 'margin-top:0px;margin-bottom:0px;'}
= form_for @user, as: :user, html: { class: 'form-horizontal user_form' } do |f|
  .agent-ID
    Agent ID
    = f.text_field :agent_id, class: '', :style => "margin-left:10px; width:130px"
  .popup-left-panel.fl
    .pic-agent{:style => "background-image:none;"}
      %img{:height => '214px', :width => '215px', :src  => @user.avatar.url(:medium)}
    .Mt{:style => "text-align:right; margin-right:10px; margin-left: -4px"}
      = f.file_field :avatar, :accept => 'image/jpeg'
    .roles#js_role_btns
      .role-heading Roles
      .role-scroll
        .Mt
          %span.select_one (Select Roles)
          %label
            = f.check_box :inherit_role, class: '', for: 'user[inherit_role]'
          %label.grouprole-inherit{:for => "user_inherit_role"} Inherit group role
        %table{:border => "1", :cellpadding => "0", :cellspacing => "0", :width => "100%"}
          %tbody
          - @roles.each do |role|
            %tr
              %td
                = hidden_field_tag "user_user_role_ids_none", nil, {:name => "user[user_role_ids][]"}
                = check_box_tag "user_user_role_ids_#{role.id}", role.id, (f.object.roles.present? and f.object.roles.include?(role)), {:name => "user[user_role_ids][]", :disabled => f.object.inherit_role ? "disabled" : false}
                = label_tag "user_user_role_ids_#{role.id}", role.name
  .popup-righr-panel.fl
    .Mb14.fl
      .form_name.fl First name
      .field.fl
        %label
          = f.text_field :first_name, style: 'width:100%;box-sizing: border-box;'
    .Mb14.fl
      .form_name.fl Last name
      .field.fl
        %label
          = f.text_field :last_name, style: 'width:100%;box-sizing: border-box;'
    .Mb14.fl
      .form_name.fl Group
      .field.fl
        %label
          = f.select :group_id, groups_list, style: 'width:100%;box-sizing: border-box;'
    .Mb14.fl
      .form_name.fl Supervisor
      .field.fl
        %label
          = f.select :supervisor_id, supervisors_list, :include_blank => 'None', style: 'width:100%;box-sizing: border-box;'
    .Mb14.fl
      .form_name.fl Department
      .field.fl
        %label
          = f.text_field :department, class: 'text_field', style: 'width:100%;box-sizing: border-box;'
    .Mb14.fl
      .form_name.fl Telephone
      .field.fl
        %label
          = f.text_field :phone, class: 'text_field', style: 'width:100%;box-sizing: border-box;'
    .Mb14.fl
      .form_name.fl E-mail
      .field.fl
        %label
          = f.text_field :email, class: 'text_field', style: 'width:100%;box-sizing: border-box;'
    .Mb14.fl
      .form_name.fl Network Login
      .field.fl
        %label
          = f.text_field :network_login, class: 'text_field', style: 'width:100%;box-sizing: border-box;'
    #js_password_fields
      / .Mb14.Mt26.fl
      .Mb14.fl
        .form_name.fl Password
        .field.fl
          %label
            = f.password_field :password, class: 'text_field', autocomplete: :off, placeholder: '********', style: 'width:100%;box-sizing: border-box;'
      .Mb14.fl
        .form_name.fl Confirm Password
        .field.fl
          %label
            = f.password_field :password_confirmation, class: 'text_field', autocomplete: :off, placeholder: '********', style: 'width:100%;box-sizing: border-box;'
    .Mb14.fl
      .form_name.fl Account Locked
      .field.fl{style: "margin-left: 4px;"}
        = f.radio_button :locked, 'true', :checked => @user.locked
        = label :user_locked, 'yes', :for => "user_locked_true"
        = f.radio_button :locked, 'false', :checked => !@user.locked, :class => "js-checkbox-false"
        = label :user_locked, 'no', :for => "user_locked_false"
    .Mb14.fl
      .form_name.fl User can change pwd
      .field.fl
        = f.radio_button :change_password, 'true', :checked => @user.change_password
        = label :user_change_password, 'yes', :for => "user_change_password_true"
        = f.radio_button :change_password, 'false', :checked => !@user.change_password, :class => "js-checkbox-false"
        = label :user_change_password, 'no', :for => "user_change_password_false"
    .Mb14.fl
      .form_name.fl Force complex pwd
      .field.fl
        = f.radio_button :complex_password, 'true', :checked => @user.complex_password
        = label :user_complex_password, 'yes', :for => "user_complex_password_true"
        = f.radio_button :complex_password, 'false', :checked => !@user.complex_password, :class => "js-checkbox-false"
        = label :user_complex_password, 'no', :for => "user_complex_password_false"
    - # Alert: SUPER_USER
    - if current_user.is_super?        
      .Mb14.fl
        .form_name.fl Super user
        .field.fl
          = f.radio_button :super_user, 'true', :checked => @user.super_user
          = label :user_super_user, 'yes', :for => "user_super_user_true"
          = f.radio_button :super_user, 'false', :checked => !@user.super_user, :class => "js-checkbox-false"
          = label :user_super_user, 'no', :for => "user_super_user_false"

app/views/users/_index.html.haml
- model_class = User
.page-header
  %h1=t '.title', :default => model_class.model_name.human.pluralize.titleize
.span6  
  %form.form-search{:action => 'users'}
    %input.input-medium.search-query#filter_users{:name => 'filter_users'}
    %button.btn Filter Users
.span2
  = link_to 'New User', new_user_path, :class => 'btn btn-primary'

%table.table.table-striped
  %thead
    %tr
      %th= 'Agent ID'
      %th= model_class.human_attribute_name(:name)
      %th= model_class.human_attribute_name(:primary_role)
      %th= model_class.human_attribute_name(:primary_group)
      %th= model_class.human_attribute_name(:network_login)
      %th= model_class.human_attribute_name(:phone_number)
      %th= model_class.human_attribute_name(:email)
      %th= model_class.human_attribute_name(:supervisor)
      %th=t '.actions', :default => t("helpers.actions")
  %tbody
    - @users.each do |user|
      %tr
        %td= link_to user.id, user_path(user)
        %td= user.name
        %td= user.type
        %td= 'Group'
        %td= user.network_login
        %td= user.phone
        %td= user.email
        %td= user.supervisor_name
        %td
          = link_to t('.edit', :default => t("helpers.links.edit")), edit_user_path(user), :class => 'btn btn-mini'
          = link_to t('.destroy', :default => t("helpers.links.destroy")), user_path(user), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-mini btn-danger'

app/views/users/_settings_form.html.haml
- if flash[:errors].try(:any?)
  #errors_container.ui-tooltip.alert.alert-error.js-alert-errors{style: "margin-left:25%; margin-top:10px;margin-bottom:10px;"}
    %h4{style: "font-size:16px;"}= "#{pluralize(flash[:errors].count, "error")} prohibited the update!"
    %p.errors.ui-tooltip{style: 'margin-top:0px;margin-bottom:0px;padding-top: 0px;padding-bottom: 2px;'}
      - flash[:errors].each do |msg|
        %p.errors.ui-tooltip{style: "margin-left:15px;padding-bottom: 0px;padding-top: 1px;font-size:14px;"}= msg
= form_for @user, as: :user, html: { class: 'form-horizontal user_form', multipart: true } do |f|
  %table{ style: "text-align: left;padding-left: 20px;border: none;font-size: 15px;vertical-align:initial;"}
    %tr
      %td{ style: "text-align: left;padding-left: 20px;border: none;font-size: 15px;vertical-align:initial;"}
        %span
          %img{:src  => @user.avatar.url(:medium), width: "180px"}
          .control-group
            %input#user_avatar{:name => "user[avatar]",  :type => "file"}/
      
      %td{ style: "text-align: left;padding-left: 20px;border: none;width:400px;font-size: 15px;"}
        %span
          .control-group
            = f.label :first_name, class: 'control-label'
            .controls
              = f.text_field :first_name, class: 'text_field'

          .control-group
            = f.label :last_name, class: 'control-label'
            .controls
              = f.text_field :last_name, class: 'text_field'

          .control-group
            = f.label :phone, class: 'control-label'
            .controls
              = f.text_field :phone, class: 'text_field'

          .control-group
            = f.label :email, class: 'control-label'
            .controls
              = f.text_field :email, class: 'text_field'
          

      %td{ style: "text-align: left;padding-left: 20px;border: none;font-size: 15px;"}
        %span
          - if @user.change_password
            .control-group
              = f.label :password, class: 'control-label'
              .controls
                = f.password_field :password, class: 'text_field', autocomplete: :off, placeholder: '********'
            
            .control-group
              = f.label :password_confirmation, class: 'control-label'
              .controls
                = f.password_field :password_confirmation, class: 'text_field', autocomplete: :off, placeholder: '********'

            .control-group
              .controls
                = f.submit 'Update', class: 'btn btn-primary'
    
    - if !@user.change_password
      %tr{ style: "background: none"}
        %td{ style: "text-align: left;padding-left: 20px;border: none;font-size: 15px;"}
        %td{ style: "text-align: left;padding-left: 20px;border: none;font-size: 15px;"}
        %td{ style: "text-align: left;padding-left: 20px;border: none;font-size: 15px;"}
          .control-group
            .controls
              = f.submit 'Update', class: 'btn btn-primary'

app/views/users/_user_profile_form.html.haml
#errors_container.ui-tooltip.alert.alert-error.js-alert-errors.hide-it{style: "margin-left:25%; margin-top:10px;margin-bottom:10px;"}
  %p.errors.ui-tooltip{style: 'margin-top:0px;margin-bottom:0px;padding-top: 0px;padding-bottom: 2px;'}
    
= form_for current_user, as: :user, html: { class: 'form-horizontal user_form', multipart: true } do |f|
  %table{ style: "text-align: left;padding-left: 20px;border: none;font-size: 15px;vertical-align:initial;"}
    %tr
      %td{ style: "text-align: left;padding-right: 30px;border: none;font-size: 15px;vertical-align:initial;"}
        %span
          %img#user_img_profile{:src  => current_user.avatar.url(:medium), width: "260px"}
          .control-group
            %input#user_avatar{:name => "user[avatar]",  :type => "file"}/
      
      %td{ style: "text-align: left;padding-left: 20px;border: none;width:400px;font-size: 15px;"}
        %span
          .control-group
            = f.label :first_name, class: 'control-label'
            .controls
              = f.text_field :first_name, class: 'text_field'

          .control-group
            = f.label :last_name, class: 'control-label'
            .controls
              = f.text_field :last_name, class: 'text_field'

          .control-group
            = f.label :phone, class: 'control-label'
            .controls
              = f.text_field :phone, class: 'text_field'

          .control-group
            = f.label :department, class: 'control-label'
            .controls
              = f.text_field :department, class: 'text_field'
          
          %span
            - if current_user.change_password
              .control-group
                = f.label :password, class: 'control-label'
                .controls
                  = f.password_field :password, class: 'text_field', autocomplete: :off, placeholder: '********'
              
              .control-group
                = f.label :password_confirmation, class: 'control-label'
                .controls
                  = f.password_field :password_confirmation, class: 'text_field', autocomplete: :off, placeholder: '********'

      / %td{ style: "text-align: left;padding-left: 20px;border: none;font-size: 15px;"}

    / - if !current_user.change_password
    /   %tr{ style: "background: none"}
    /     %td{ style: "text-align: left;padding-left: 20px;border: none;font-size: 15px;"}
    /     %td{ style: "text-align: left;padding-left: 20px;border: none;font-size: 15px;"}
    /     %td{ style: "text-align: left;padding-left: 20px;border: none;font-size: 15px;"}

app/views/users/edit.html.haml
- model_class = User
.page-header
  %h1=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

app/views/users/new.html.haml
- model_class = User
.page-header
  %h1=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

app/views/users/show.html.haml
- model_class = User
.page-header
  %h1=t '.title', :default => model_class.model_name.human.titleize

%p
  %strong= model_class.human_attribute_name(:email) + ':'
  %br
  = @user.email
%p
  %strong= model_class.human_attribute_name(:type) + ':'
  %br
  = @user.type

.form-actions
  = link_to t('.back', :default => t("helpers.links.back")), users_path, :class => 'btn'
  = link_to t('.edit', :default => t("helpers.links.edit")), edit_user_path(@user), :class => 'btn'
  = link_to t('.destroy', :default => t("helpers.links.destroy")), user_path(@user), :method => "delete", :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-danger'