config/routes.rb
QualityCloud::Application.routes.draw do

  get 'calls/:call_id/notes' => "call_notes#call_notes"
  resources :call_notes

  get '/users/:user_id/saved_search_tabs' => "saved_search_tabs#user_saved_tabs"
  get '/users/current_user_saved_search_tabs' => "saved_search_tabs#current_user_saved_tabs"
  resources :saved_search_tabs

  match '/organization' => "home#personal", as: :personal_tab
  match '/search' => "home#search", as: :search_tab
  get '/settings' => "home#settings", as: :settings_tab
  
  resources :roles do
    member do
      put :set_permissions
    end
  end
  
  match "/permissions" => "roles#permissions"

  resources :groups do
    resources :users, only: [] do
      collection do
        get "/", action: :group_members
      end
    end
  end

  get 'calls/download_calls' => "calls#download_calls"
  get 'calls/:id/stream_video' => "calls#stream_video"
  get 'calls/:id/stream_audio' => "calls#stream_audio"
  match '/calls/search' => "calls#search"
  match '/calls/load_calls' => "calls#load_calls"
  resources :calls do 
    member do
      get :status
    end
  end

  resources :dashboard, only: [ :index ]
  resources :searches, only: [ :index, :create ], controller: :search, path: '/search'

  get '/admin/users/:id/user_avatar/:type' => "users#user_avatar"
  get '/admin/users/user_names' => "users#user_names"
  scope :admin, path: '/admin' do
    resources :users do
      collection { post :import }
    end
  end
  
  devise_for :users, :controllers => { :passwords => "passwords" }
  authenticated :user do
    root :to => 'home#search'
  end
  get "home/email_confirmation" => "home#email_confirmation"

  unauthenticated :user do
    devise_scope :user do 
      get "/" => "devise/sessions#new"
    end
  end

  resources :assigned_roles
  resources :role_accesses

end

app/models/role.rb
class Role < ActiveRecord::Base
  attr_accessible :name, :permissions, :supervisable, :disabled
  attr_accessor :new_role_id
  serialize :permissions, Array

  validates :name, :presence => true
  validates :name, :uniqueness => {:case_sensitive => false}

  has_many :assigned_roles
  has_many :assigned_groups, through: :assigned_roles, conditions: {roleable_type: 'Group'}
  has_many :assigned_users, through: :assigned_roles, conditions: {roleable_type: 'User'}

  has_many :role_accesses, dependent: :destroy
  has_many :accessed_groups, through: :role_accesses, conditions: {accessable_type: 'Group'}
  has_many :accessed_users, through: :role_accesses, conditions: {accessable_type: 'User'}

  before_destroy :check_deleted_role
  before_save :check_preset_roles_attributes

  default_scope order('roles.name ASC')

  def check_deleted_role
    if name == configatron.default_role_name
      self.errors[:base] << "Cannot delete '#{configatron.default_role_name}' role."
      return false 
    # Alert: SUPER_USER
    elsif name == configatron.super_role_name  
      self.errors[:base] << "Cannot delete '#{configatron.super_role_name}' role."
      return false 
    else
      replacement_role = Role.where(:id => self.new_role_id).first ||
        Role.find_by_name(configatron.default_role_name)
      groups.each do |group| 
        group.update_attribute(:role_ids, [replacement_role.id]) unless group.has_other_role?(self)
      end
      users.each do |user| 
        user.update_attribute(:user_roles, [replacement_role]) unless user.has_other_role?(self)
      end
    end 
  end

  # Alert: SUPER_USER
  def check_preset_roles_attributes
    # make sure that the preset roles aren't changed
    if self.name_was == configatron.super_role_name
      self.name = configatron.super_role_name
    elsif self.name_was == configatron.default_role_name
      self.name = configatron.default_role_name
    end
  end

  scope :supervisable, where(:supervisable => true)
  scope :disabled, where(:disabled => true)
  scope :enabled, where(:disabled => false)

  def groups
    Group.find assigned_roles.where(roleable_type: 'Group').map{|r| r.roleable_id}
  end

  def users
    User.find assigned_roles.where(roleable_type: 'User').map{|r| r.roleable_id}
  end

  def can_delete?
  end

  def as_json(*args)
    hash = super(*args)
    hash.merge!({:permissions => self.permissions})
    hash
  end

end

# == Schema Information
#
# Table name: roles
#
#  id           :integer          not null, primary key
#  name         :string(255)      default(""), not null
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#  permissions  :integer
#  supervisable :boolean
#  disabled     :boolean          default(FALSE)
#

app/controllers/roles_controller.rb
class RolesController < ApplicationController
  before_filter :selected_item
  load_and_authorize_resource
  # GET /roles
  # GET /roles.json
  def index
    @roles = Role.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @roles }
    end
  end

  # GET /roles/1
  # GET /roles/1.json
  def show
    @role = Role.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @role }
    end
  end

  # GET /roles/new
  # GET /roles/new.json
  def new
    @role = Role.new

    respond_to do |format|
      format.html { render partial: 'form', layout: false }
      format.json { render json: @role }
    end
  end

  # GET /roles/1/edit
  def edit
    @role = Role.find(params[:id])

    if @role.blank?
      "Role doesn't exist"
    else
      respond_to do |format|
        format.html { render partial: 'form', layout: false }
        format.json { render json: @role }
      end
    end
  end

  # POST /roles
  # POST /roles.json
  def create
    @role = Role.new(params[:role])

    respond_to do |format|
      if @role.save
        format.html { redirect_to @role, notice: 'Role was successfully created.' }
        format.json { render json: @role, status: :created }
      else
        format.html { render action: "new" }
        format.json { render json: @role.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /roles/1
  # PUT /roles/1.json
  def update
    @role = Role.find(params[:id])
    params[:role].delete :permissions

    respond_to do |format|
      if @role.update_attributes(params[:role])
        format.html { redirect_to @role, notice: 'Role was successfully updated.' }
        format.json { render json: @role, status: :created }
      else
        format.html { render action: "edit" }
        format.json { render json: @role.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /roles/1
  # PUT /roles/1.json
  def set_permissions
    @role = Role.find(params[:id])
    params[:role].slice! :permissions
    respond_to do |format|
      if @role.update_attributes(params[:role])
        format.html { redirect_to @role, notice: 'Role was successfully updated.' }
        format.json { render json: @role, status: :created }
      else
        format.html { render action: "edit" }
        format.json { render json: @role.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /roles/1
  # DELETE /roles/1.json
  def destroy
    @role = Role.find(params[:id])
    @role.new_role_id = params[:new_role_id]
    @role.destroy

    respond_to do |format|
      format.html { redirect_to roles_url }
      format.json { head :no_content }
    end
  end

  def permissions
    render json: Permission::PERMISSIONS
  end

  private
  def selected_item
    @selected = :personal
    @sub_menue = :roles
  end
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/views/roles/_form.html.haml
#errors_container.ui-tooltip.alert.alert-error.js-alert-errors.hide-it{style:"max-width: 300px;margin: 10px;"}
  %h4 Errors!
  %p.errors.ui-tooltip{style: 'margin-top:0px;margin-bottom:0px;'}
= form_for @role do |f|
  .control-group.nw-gurp-role-top
    = f.label "Role Name", class: 'control-label'
    .nw-gurp-role-inpt
      = f.text_field :name, class: 'text_field'
  .new-role-option-wrapper
    .available-users-group.boxLayout
      .available-users.fl Options
      .w-100.fl
        .list-white.fl
          = f.check_box :supervisable, class: 'text_field'
          = f.label 'This role contains supervisor agents', class: 'control-label', for: "role_supervisable"
        .list-grey.fl
          = f.check_box :disabled, class: 'text_field'
          = f.label 'Disable role', class: 'control-label', for: "role_disabled"
        %br
        / Hidden submit button, to allow submit form on enter key
        .hidden-submit
          %input{:type => "submit", :tabindex => -1}

app/views/roles/edit.html.haml
%h1 Editing role

= render 'form'

= link_to 'Show', @role
\|
= link_to 'Back', roles_path

app/views/roles/index.html.haml
- model_class = Role

%table.table.table-striped
  %thead
    %tr
      %th= model_class.human_attribute_name(:name)
      %th=t '.actions', :default => t("helpers.actions")
  %tbody
    - @roles.each do |role|
      %tr
        %td= link_to role.name, role_path(role)
        %td
          = link_to t('.edit', :default => t("helpers.links.edit")), edit_role_path(role), :class => 'btn btn-mini'
          = link_to t('.destroy', :default => t("helpers.links.destroy")), role_path(role), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-mini btn-danger'
%br

= link_to 'New Role', new_role_path, :class => 'btn'

app/views/roles/new.html.haml
%h1 New role

= render 'form'

= link_to 'Back', roles_path

app/views/roles/show.html.haml
%p#notice= notice


= link_to 'Edit', edit_role_path(@role)
\|
= link_to 'Back', roles_path